### ISSUE TITLE
Improve formatting of filestore preview

### ISSUE THREAD

**Issue by nvnikolov** [datagraft/datagraft-portal#50]
- [x] Improve how the tabular preview of data is displayed in file pages
- [x] Provide a way to navigate back to the file page (consider showing the preview in the same window)

**Comment by sdalgard** [comment]
Implemented with same layout as for query result using DataTables.js

**Comment by sdalgard** [comment]
The proeview page is open in a new window/tab and can be closed when ready.
A back button will not have a meaning.

It is not wanted to always read the file to generate a preview since that process may require fetching the file from a remote server.
Adding show in the same window will require use of AJAX or total reload of the page.

**Comment by sdalgard** [comment]
Done
